### PR TITLE
Fix failing tests on non-UK/US locales

### LINKED ISSUE #1867: gradlew build failing on pc with Locale using commas
### Description
Build is failing on pc with a Belgian locale because some unit test depend on the locale using dots in numbers and not commas.

### To Reproduce
1. Set the locale on your pc to en_BE
2. run ./gradlew clean build

### Expected behavior
No tests failing

### Desktop (please complete the following information):
 - OS: MacOS
 - QuPath Version: 1d3f9980804923dfc9e207cbfad2a7f1ff545c37

### Additional context
One of the 2 unit test files failing is TestParameterList.java, in this case the test uses `GeneralTools.parseArgStringValues(json)`, which coverts the values in the json to string values without taking the locale into account. 
This then causes a problem because a bit later in the test, `ParameterList.updateParameterList(paramsFromJson, mapFromJson, Locale.getDefault())` is used, which is using the locale of the host machine.

### PR DESCRIPTION
**Pull request by alanocallaghan**
Resolve #1867

### CODE REVIEW

File: qupath-core/src/test/java/qupath/lib/plugins/parameters/TestParameterList.java [hunk 1]
```diff
@@ -98,7 +98,7 @@ void testJson() {
 		assertNotEquals(json, jsonDifferent);
 
 		// Update the values, then check again
-		ParameterList.updateParameterList(paramsFromJson, mapFromJson, Locale.getDefault());
+		ParameterList.updateParameterList(paramsFromJson, mapFromJson, Locale.UK);
```
Comment (petebankhead) [inline qupath-core/src/test/java/qupath/lib/plugins/parameters/TestParameterList.java:101]: QuPath's default is US - see https://github.com/search?q=repo%3Aqupath%2Fqupath%20locale.us&type=code

Comment (alanocallaghan) [reply qupath-core/src/test/java/qupath/lib/plugins/parameters/TestParameterList.java:101]:
```suggestion
		ParameterList.updateParameterList(paramsFromJson, mapFromJson, Locale.US);
```

**Comment by alanocallaghan** [comment]
Tagging in Leo to see if there is a better way to handle testing multiple locales

**Review by Rylern — APPROVED** [review]
Looks good to me, I didn't know the use of `ParameterizedTest`
